// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXrYOQC-C-FqljbdFZKCIOqZcKA6onqSk',
    appId: '1:427363889607:web:1262b6f8367e90017129e2',
    messagingSenderId: '427363889607',
    projectId: 'aplikasi-uas-1432d',
    authDomain: 'aplikasi-uas-1432d.firebaseapp.com',
    storageBucket: 'aplikasi-uas-1432d.firebasestorage.app',
    measurementId: 'G-N9KY20BXW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD58MNsKmCjo47Yca79B5hxEDEPRYaCszQ',
    appId: '1:427363889607:android:0564d40d920e3a787129e2',
    messagingSenderId: '427363889607',
    projectId: 'aplikasi-uas-1432d',
    storageBucket: 'aplikasi-uas-1432d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTlChYbHJA8a5hEoc7FvqrzSihkWxb4b4',
    appId: '1:427363889607:ios:c390d3856c78bb7d7129e2',
    messagingSenderId: '427363889607',
    projectId: 'aplikasi-uas-1432d',
    storageBucket: 'aplikasi-uas-1432d.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTlChYbHJA8a5hEoc7FvqrzSihkWxb4b4',
    appId: '1:427363889607:ios:c390d3856c78bb7d7129e2',
    messagingSenderId: '427363889607',
    projectId: 'aplikasi-uas-1432d',
    storageBucket: 'aplikasi-uas-1432d.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiUas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXrYOQC-C-FqljbdFZKCIOqZcKA6onqSk',
    appId: '1:427363889607:web:2abb183c0527a5d17129e2',
    messagingSenderId: '427363889607',
    projectId: 'aplikasi-uas-1432d',
    authDomain: 'aplikasi-uas-1432d.firebaseapp.com',
    storageBucket: 'aplikasi-uas-1432d.firebasestorage.app',
    measurementId: 'G-JZM9M0QNFS',
  );
}
